version: "3"

services:
  asset_server:
    container_name: asset_server
    build: .
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      MONGO_URL:  mongodb://rsAdmin:raj123@mongo1:27017,mongo2:27017,mongo3:27017/EvModel?replicaSet=mongoReplica&w=1
      ESTIMATE_URL: http://estimate:5000/estimate

    networks:
      - dockeriseevsetup_asset_network
         
networks:
  dockeriseevsetup_asset_network:
    external: true
