version: "3"

services:
  asset_server:
    container_name: asset_server
    build: .
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      MONGO_URL:  mongodb://mongo1:27017,mongo2:27017,mongo3:27017/EvModel?replicaSet=mongoReplica&w=1
      ESTIMATE_URL: http://estimate:5000/estimate
      
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - asset_network

networks:
  asset_network:
    driver: bridge

volumes:
  mongo1: {}
  mongo2: {}
  mongo3: {}

