version: "3"

services:
  mongo_db:
    container_name: mongo_database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
    networks:
      - asset_network

  asset_server:
    build: .
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      MONGO_URL: mongodb://mongo_db:27017/EvModel
      ESTIMATE_URL: http://estimate:5000/estimate
      
    depends_on:
      - mongo_db
    networks:
      - asset_network

networks:
  asset_network:
    driver: bridge

volumes:
  mongo_db: {}
